### PR TITLE
benchmark/message api; refactored benchmarks

### PR DESCRIPTION
**Pull request by artem-v**
Here's new PR branched from ``benchmark/message_api`` with refactored tests and applied code review comments from PR#25.

### CODE REVIEW

**Comment by artem-v** [comment]
```
Benchmark                                             Mode  Samples    Score    Error  Units
c.CacheReadBenchmark.readFromGuavaCache               avgt       10  747.937 ? 35.393  ns/op
c.CacheReadBenchmark.readFromGuavaWithCacheMiss       avgt       10  763.296 ? 17.116  ns/op
c.CacheReadBenchmark.readFromMemoizer                 avgt       10  162.067 ?  5.110  ns/op
c.CacheReadBenchmark.readFromMemoizerWithCacheMiss    avgt       10  167.944 ?  7.528  ns/op

Benchmark                                       Mode  Samples     Score     Error  Units
i.s.t.p.ProtostuffMessageBenchmark.deser_x1     avgt       10  2502.197 ? 204.491  ns/op
i.s.t.p.ProtostuffMessageBenchmark.deser_x10    avgt       10  2624.832 ? 232.219  ns/op
i.s.t.p.ProtostuffMessageBenchmark.ser_x1       avgt       10  1232.118 ?  29.021  ns/op
i.s.t.p.ProtostuffMessageBenchmark.ser_x10      avgt       10  1254.680 ?  38.812  ns/op

Benchmark                                       Mode  Samples       Score      Error  Units
i.s.c.g.ProtostuffGossipBenchmark.deser_x10     avgt       10   19618.147 ? 3220.832  ns/op
i.s.c.g.ProtostuffGossipBenchmark.deser_x100    avgt       10  199932.419 ? 3992.492  ns/op
i.s.c.g.ProtostuffGossipBenchmark.ser_x10       avgt       10   12206.290 ?  250.545  ns/op
i.s.c.g.ProtostuffGossipBenchmark.ser_x100      avgt       10  110574.828 ? 1580.093  ns/op

```

**Comment by antonkharenko** [comment]
Still need to fix Travis build

**Comment by artem-v** [comment]
@antonkharenko yep

**Comment by artem-v** [comment]
``CacheReadBenchmark`` refactored, also applied Konstantin' comment and removed ```expireAfterAccess```. And still ``memoizer`` performs much better. Fail cases not affect much (_...WithCacheMiss_ though not a good name).

**Comment by artem-v** [comment]
In the ``ProtostuffMessageBenchmark`` there're two kinds of tests: _x1(regular message 128b) and _x10(big message ~ 1k). Message payload consists not from ```byte[]``` like it was earlier, but from ```ImmutableList```.

**Comment by artem-v** [comment]
Upon ``ProtostuffGossipBenchmark``. There're two tests: _x10 and _x100 meaning ``GossipRequest`` has 10 or 100 gossips inside. Each message payload is ``ImmutableList`` of ``byte[]``  plus  headers. Spial note here: _x10 and _x100 are comparable in size and should be ~ 1k each. Test show how we deal with many small objects  comparing  to few objects; but in total eq in size.

**Comment by artem-v** [comment]
New tests results (now with output serialized size):

```
Benchmark                                       Mode  Samples     Score     Error  Units
i.s.t.p.ProtostuffMessageBenchmark.deser        avgt       10  1908.885 � 116.014  ns/op
i.s.t.p.ProtostuffMessageBenchmark.deser_x16    avgt       10  4572.752 � 366.644  ns/op
i.s.t.p.ProtostuffMessageBenchmark.ser          avgt       10  1057.564 �  25.792  ns/op
i.s.t.p.ProtostuffMessageBenchmark.ser_x16      avgt       10  5366.211 �  50.307  ns/op

### msg_ser=UnpooledHeapByteBuf(ridx: 0, widx: 58, cap: 1024)
### msg_x16_ser=UnpooledHeapByteBuf(ridx: 0, widx: 540, cap: 1024)

------------------

Benchmark                                      Mode  Samples      Score      Error  Units
i.s.c.g.ProtostuffGossipBenchmark.deser        avgt       10   8236.387 �  349.903  ns/op
i.s.c.g.ProtostuffGossipBenchmark.deser_x32    avgt       10  54574.124 � 1532.163  ns/op
i.s.c.g.ProtostuffGossipBenchmark.ser          avgt       10   7851.008 �   68.781  ns/op
i.s.c.g.ProtostuffGossipBenchmark.ser_x32      avgt       10  32059.614 �  590.779  ns/op

### gossipReq_ser=UnpooledHeapByteBuf(ridx: 0, widx: 1118, cap: 2048)
### gossipReq_x32_ser=UnpooledHeapByteBuf(ridx: 0, widx: 2440, cap: 4096)

```

**Comment by antonkharenko** [comment]
+1

**Pull request merged**
